# Server Port
server.port=8080

# SQL Server Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QueenBeautiful;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=your_password
spring.datasource.driver-className=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
